### ISSUE TITLE
REQUEST: User Controlled Save Location

### ISSUE THREAD

**Issue by 7ranceaddic7** [linuxgurugamer/KSPLogger#5]
Currently, datalog.* files are logged directly to <ksproot> and while, easy to identify, clutter the root directory.

Many mods are using <ksproot>/Logs (started by MM) as a location for their log files.
![image](https://user-images.githubusercontent.com/4062616/90288497-d87aa680-de2e-11ea-95d2-401921ea873e.png)

It would be nice to be able to designate a (or at least have this location defaulted) folder of choice for these files.

Suggestion:
1. Institute a configurable save location.
2. Set default to <ksproot>/Logs/KSPLogger (highlighted)

![image](https://user-images.githubusercontent.com/4062616/90288411-b08b4300-de2e-11ea-9cdf-e8e7ae9d1ac3.png)

**Comment by linuxgurugamer** [comment]
Did you read the documentation?  Did you read the config file?

From the OP:

There is a config file called PluginData/KSPLogger_default.cfg, which contains all the value which can be set.  Copy that file to:  PluginData/KSPLogger.cfg and change that; the default will be overwritten when new versions come out, but your config will remain safe,

In that file, you can specify where the files go by updating the filePrefix, which is the Prefix of the file name.  In other words, you can specify an absolute path if you like.

For example:

This is the line from my config, which I use when I'm streaming:

 filePrefix = r:/OBS/dataLog_	// Prefix of file name.  This starts in the root of the game, you can specify subdirectories if you like

and my files are put onto the R drive, in a directory called OBS

**Comment by 7ranceaddic7** [comment]
LoL, just came to close this out.

I did read, but for some reason didn't put it together.

Then, I had a brilliant idea 💡, what if I changed the file prefix to include redirection...

**Comment by linuxgurugamer** [comment]
I will add a little more explanation to the file
